"""empty message

Revision ID: 98b194e9e98d
Revises: 0b72d3cefeeb
Create Date: 2019-06-23 15:02:13.816508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b194e9e98d'
down_revision = '0b72d3cefeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('devices', 'dscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('dscription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('devices', 'description')
    # ### end Alembic commands ###
